Feat: profile api on client
Filimonsha/snake-game pull request #21
Opened 2023-03-11 17:06 UTC by ff1892

### Какую задачу решаем

Подключем апи профиля на клиенте: смена данных профиля, пароля и аватарки.

2023-03-12 20:45 UTC, anastasia-shmeleva approved these changes

2023-03-12 20:49 UTC, Filimonsha approved these changes

2023-03-12 20:50 UTC, ValekP approved these changes

2023-03-13 08:57 UTC, DazzlingFame commented
Привет, поправь конфликты в ветке, пожалуйста

2023-03-13 09:02 UTC, ff1892 commented
> Привет, поправь конфликты в ветке, пожалуйста

@DazzlingFame Привет! Готово

2023-03-13 12:22 UTC, DazzlingFame commented
Привет, пробежался мельком по коду, появилисб ещё вопросы: 
вижу в этом пр 
- закомменченный код (например в packages/client/src/store/api/yadnex/yandexBaseQuery.ts) 
- и частичный дубль функциональности (например реализации RequireAuth) относительно вот [этого ПР](https://github.com/Filimonsha/snake-game/pull/20) 

Собственно вопросы:
1. В чем цель влития комментов в мастер? 
2. Может подождать влития https://github.com/Filimonsha/snake-game/pull/20, чтобы синхронизировать код?

2023-03-13 12:45 UTC, ff1892 commented
@DazzlingFame поправил

RequireAuth мы писали вместе, потом каждый добавил в свою ветку, чтобы можно было работать над задачей. У нас небольшая путаница произошла, сейчас как раз хотим навести порядок и внести всю текущую работу в dev.

1. Комменты, как оказалось, не нужны: мы думали, как будем передавать токен на сервер, чтобы закрыть апи авторизацей - это у нас давно лежит в коде, заготовка для настройки заголовков, но решили иначе
2. Конечно, как 20 пр  будет смерджен, я добавлю этот (после апрува)

2023-03-14 10:41 UTC, ff1892 commented
@DazzlingFame привет еще раз! Ответил на коммент, поправил конфликты. Посмотри, пожалуйста

2023-03-14 11:39 UTC, DazzlingFame approved these changes
Привет, пробежался, оставил комментарии

2023-03-14 11:39 UTC, DazzlingFame commented on packages/client/src/hooks/requireAuth.tsx
> +export const RequireAuth = ({ children }: { children: JSX.Element }) =>{
насколько я понимаю, в твоей ветке RequireAuth и useAuth сейчас дублируются в разных частях проекта

на скрине они же добавлены в другом пр в другое место

<img width="791" alt="image" src="https://user-images.githubusercontent.com/15292833/224987900-0b03f425-fe37-4895-be09-91e7db1b4f55.png">

2023-03-14 11:39 UTC, DazzlingFame commented on packages/client/src/pages/main/modules/profile/Profile.tsx
> +      if ('data' in res) {
а так тут не сработает? Выглядит проще
```suggestion
      if (res.data) {
```

2023-03-14 11:39 UTC, DazzlingFame commented on packages/client/src/pages/main/modules/profile/components/AvatarModal/AvatarModal.tsx
> +      toast.error(`${error}`);
Тут не хватает человекочитаемого описания для юзера о том, что произошло

2023-03-14 11:39 UTC, DazzlingFame commented on packages/client/src/pages/main/modules/profile/components/AvatarModal/AvatarModal.tsx
> +      toast.error(`${error}`);
Тут не хватает человекочитаемого описания для юзера о том, что произошло

2023-03-14 11:39 UTC, DazzlingFame commented on packages/client/src/pages/main/modules/profile/components/AvatarModal/AvatarModal.tsx
> +      if ('data' in res) {
?
```suggestion
      if (res.data) {
```

2023-03-14 11:39 UTC, DazzlingFame commented on packages/client/src/pages/main/modules/profile/components/AvatarModal/AvatarModal.tsx
> +      if ('data' in res) {
ниже тут тот же вопрос

2023-03-14 11:39 UTC, DazzlingFame commented on packages/server/modules/auth/auth.controller.ts
> +    console.log(currentUser)
этот лог нужен пользователям?

2023-03-14 11:39 UTC, DazzlingFame commented on packages/client/src/pages/main/modules/profile/components/AvatarModal/AvatarModal.tsx
> +      toast.error(`${error}`);
Посмотри сразу во всем ПР, в других файлах дальше тоже вижу такие места

2023-03-14 11:39 UTC, DazzlingFame requested changes
Мисклик на апрув)

2023-03-14 11:44 UTC, anastasia-shmeleva commented on packages/client/src/pages/main/modules/profile/Profile.tsx
> +      if ('data' in res) {
У меня был тот же момент, res.data был с ошибкой, она уходит если добавить типизацию
const res: any = await changeProfile(userData);

Альтернативу any правда, не смогла подобрать, не уверена что в итоге лучше

2023-03-14 12:59 UTC, ff1892 commented on packages/client/src/hooks/requireAuth.tsx
> +export const RequireAuth = ({ children }: { children: JSX.Element }) =>{
Удалил папку hooks. В бесконечном мерджинге из мастера не увидел (

2023-03-14 13:02 UTC, ff1892 commented on packages/client/src/pages/main/modules/profile/Profile.tsx
> +      if ('data' in res) {
Согласен с @anastasia-shmeleva 

Этот результат из хука, него тип:

![Снимок экрана 2023-03-14 в 15 27 54](https://user-images.githubusercontent.com/64530309/225008603-ebe8f58f-97cb-4f4f-879d-27f4d6443fd5.png)

К тому же проверка res.data не гарантирует, что это поле есть:

```
const res = { data: 0 }
if (res.data) console.log('no print')
if ('data' in res) console.log('print') 
```

2023-03-14 13:04 UTC, ff1892 commented on packages/client/src/pages/main/modules/profile/components/AvatarModal/AvatarModal.tsx
> +      toast.error(`${error}`);
Заменил на сообщение. Но выше по коду выбрасывалось ошибка с сообщением-строкой, а catch ее подхватывал.

![Снимок экрана 2023-03-14 в 15 49 03](https://user-images.githubusercontent.com/64530309/225009375-cf76f581-f275-499e-b58a-1eb3e5c9fe8e.png)

2023-03-14 13:05 UTC, ff1892 commented on packages/client/src/pages/main/modules/profile/components/AvatarModal/AvatarModal.tsx
> +      toast.error(`${error}`);
Done

2023-03-14 13:05 UTC, ff1892 commented on packages/client/src/pages/main/modules/profile/components/AvatarModal/AvatarModal.tsx
> +      if ('data' in res) {
ответил выше

2023-03-14 13:05 UTC, ff1892 commented on packages/server/modules/auth/auth.controller.ts
> +    console.log(currentUser)
удалил

2023-03-14 13:06 UTC, ff1892 commented
@DazzlingFame пофиксил и ответил на комменты

2023-03-15 07:38 UTC, DazzlingFame commented on packages/client/src/pages/main/modules/profile/Profile.tsx
> +      if ('data' in res) {
Ок, если вам тут нужна проверка именно на то, что поле есть, а не на то, что в нём есть какой-то контент, то такая проверка вполне оправдана

2023-03-15 07:40 UTC, DazzlingFame approved these changes
Привет, круто, что всё быстро поправил, ставлю апрув.

2023-03-15 07:53 UTC, merged